<!DOCTYPE html>
<html lang="en">
  <head>
    <?include_once 'includes/head.inc'; ?>
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">

        <?include_once 'includes/sidebar.inc'; ?>

        <!-- top navigation -->
        <?include_once 'includes/topnav.inc'; ?>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">

          <div class="x_content">
            <h3><?=$page_title;?></h3> <button class="btn btn-danger" onclick="window.location.href='<?=base_url('Products/add_product');?>'"><i class="fab fa-product-hunt"></i> Add New Product</button>
            <table class="table table-striped table-hover table-bordered" id="data-table">
              <thead>
                <tr>
                  <th>Barcode</th>
                  <th>Product Name</th>
                  <th>Category Name</th>
                  <th>Date Generated</th>
                  <th>Generated By</th>
                  <th>Options</th>
                </tr>
              </thead>
              <tbody>
                <?
                if( empty($products_and_barcodes) ){?>
                  <tr>
                    <td colspan="7">No data to display</td>
                  </tr>
                <?} else {
                  //echo "<pre>";print_r($all_users);exit;
                  foreach ($products_and_barcodes as $key => $value) {
                    $product_id = $value["product_id"];
                    ?>
                    <tr>
                      <td><?=$value["barcode"];?></td>
                      <td><?=$value["product_name"];?></td>
                      <td><?=$value["category_name"];?></td>
                      <td><?= date("M d, Y", strtotime($value["date_generated"]));?></td>
                      <td><?=$value["generated_by"];?></td>
                      <td>
                        <a href="<?=base_url('Products/view_generated_barcode/' . $product_id)?>" title="Details"><i class="fas fa-file-alt"></i></a>                        
                      </td>
                    </tr>
                  <?}
                }
                ?>
              </tbody>
            </table>
          </div>
          <!-- top tiles -->



        </div>
        <!-- /page content -->

        <!-- footer content -->
        <?include_once 'includes/footer.inc';?>
        <!-- /footer content -->
      </div>
    </div>

    <!-- jQuery -->
    <?include_once 'includes/scripts.inc';?>
    <?include_once 'includes/data-table-scripts.inc';?>
    <script type="text/javascript">
      $(document).ready(function() {
          $('#data-table').DataTable({
            "pageLength": 100,
            dom: 'Bfrtip',
            buttons: [
                'copyHtml5', 'csvHtml5', 'excelHtml5', 'pdfHtml5', 'print'
            ]
          });
      } );
    </script>

  </body>
</html>
