<link href="<?=base_url('assets/css/dataTables.bootstrap.min.css');?>" rel="stylesheet">
<link href="<?=base_url('assets/css/buttons.bootstrap.min.css');?>" rel="stylesheet">
<link href="<?=base_url('assets/css/fixedHeader.bootstrap.min.css');?>" rel="stylesheet">
<link href="<?=base_url('assets/css/responsive.bootstrap.min.css');?>" rel="stylesheet">
<link href="<?=base_url('assets/css/scroller.bootstrap.min.css');?>" rel="stylesheet">