<script src="<?=base_url('assets/js/jquery.dataTables.min.js');?>"></script>
<script src="<?=base_url('assets/js/dataTables.buttons.min.js');?>"></script>
<script src="<?=base_url('assets/js/buttons.flash.min.js');?>"></script>
<script src="<?=base_url('assets/js/jszip.min.js');?>"></script>
<script src="<?=base_url('assets/js/pdfmake.min.js');?>"></script>
<script src="<?=base_url('assets/js/buttons.html5.min.js');?>"></script>
<script src="<?=base_url('assets/js/buttons.print.min.js');?>"></script>

<script src="<?=base_url('assets/js/dataTables.bootstrap.min.js');?>"></script>
<script src="<?=base_url('assets/js/dataTables.fixedHeader.min.js');?>"></script>
<script src="<?=base_url('assets/js/dataTables.keyTable.min.js');?>"></script>
<script src="<?=base_url('assets/js/dataTables.responsive.min.js');?>"></script>
<script src="<?=base_url('assets/js/responsive.bootstrap.js');?>"></script>
<script src="<?=base_url('assets/js/dataTables.scroller.min.js');?>"></script>


<script src="<?=base_url('assets/js/buttons.bootstrap.min.js');?>"></script>





<script src="<?=base_url('assets/js/vfs_fonts.js');?>"></script>